export const detallesCita: Array<string> = [
  'Control de rutina para verificar el estado general del paciente.',
  'Evaluación de progreso en el plan alimenticio implementado.',
  'Primera consulta para conocer antecedentes y hábitos.',
  'Seguimiento mensual de evolución física y alimentación.',
  'Chequeo general para descartar deficiencias nutricionales.',
  'Revisión de análisis laboratoriales entregados previamente.',
  'Control de peso y ajuste de calorías diarias recomendadas.',
  'Consulta por malestar estomacal relacionado con la dieta.',
  'Ajuste del plan alimentario según nuevos objetivos del paciente.',
  'Evaluación nutricional con medición de parámetros corporales.',
  'Consulta por molestias digestivas recurrentes.',
  'Revisión post tratamiento dietético aplicado el mes anterior.',
  'Seguimiento de los objetivos planteados en la cita anterior.',
  'Control de presión arterial y peso corporal.',
  'Asesoramiento sobre combinaciones de alimentos saludables.',
  'Consulta por episodios frecuentes de fatiga sin causa aparente.',
  'Orientación sobre selección de alimentos en el mercado.',
  'Control trimestral de resultados clínicos y hábitos adquiridos.',
  'Revisión del progreso en el control del apetito emocional.',
  'Planificación semanal de comidas según preferencias del paciente.',
  'Consulta por irregularidades digestivas leves.',
  'Evaluación de hábitos alimentarios diarios y recomendaciones.',
  'Monitoreo del plan de reducción de grasa corporal.',
  'Control de peso bajo persistente y revisión calórica.',
  'Revisión tras periodo vacacional con desorden alimenticio.',
  'Consulta por sospecha de intolerancia alimentaria leve.',
  'Cita de seguimiento para reforzar buenos hábitos adquiridos.',
  'Evaluación de síntomas que afectan la digestión diaria.',
  'Revisión de efectividad del régimen alimenticio actual.',
  'Consulta preventiva antes de iniciar actividad física.',
  'Control anual con mediciones corporales y revisión general.',
  'Valoración del estado nutricional con parámetros antropométricos.',
  'Discusión sobre ajustes en el estilo de vida saludable.',
  'Asesoría personalizada en planificación de comidas.',
  'Consulta por ansiedad relacionada con la alimentación.',
  'Seguimiento de parámetros por dieta baja en colesterol.',
  'Revisión por náuseas ocasionales después de las comidas.',
  'Consulta por retención de líquidos y posible origen dietético.',
  'Control post quirúrgico con adaptación de dieta progresiva.',
  'Revisión de hábitos poco saludables detectados previamente.',
  'Consulta por aumento del apetito fuera de lo común.',
  'Evaluación de cambios recientes en peso sin razón aparente.',
  'Asesoramiento sobre uso adecuado de suplementos nutricionales.',
  'Chequeo de rutina con refuerzo de indicaciones previas.',
  'Control de presión en pacientes con historial hipertensivo.',
  'Consulta por reflujo y ajustes en el consumo de alimentos.',
  'Seguimiento de dieta para pacientes con diagnóstico de diabetes.',
  'Control de cumplimiento de metas semanales establecidas.',
  'Evaluación post cambio de plan alimentario.',
  'Consulta por dolor abdominal leve y cambios alimenticios recientes.',
]
export function obtenerElementoAleatorio<T>(array: T[]): T | undefined {
  if (array.length === 0) return undefined
  const indiceAleatorio = Math.floor(Math.random() * array.length)
  return array[indiceAleatorio]
}
