import { AlimentoEstado } from '@/application/planes-alimentarios/constant'
import {
  Alimento,
  TipoAlimento,
} from '@/application/planes-alimentarios/entity/alimento.entity'
import { USUARIO_SISTEMA } from '@/common/constants'
import { MigrationInterface, QueryRunner } from 'typeorm'

export class CrearAlimentos1748188643089 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const items = [
      {
        urlImage: '',
        nombre: 'Avena con leche',
        descripcion: 'Avena cocida en leche con fruta picada',
        tipo: TipoAlimento.DESAYUNO,
        calorias: 250,
        grasa: 8,
        carbohidratos: 40,
        proteinas: 10,
        receta:
          '<div>Ingredientes: avena, leche, fruta. Preparación: hervir avena con leche, agregar fruta picada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Manzana y nueces',
        descripcion: 'Manzana fresca con nueces',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 150,
        grasa: 7,
        carbohidratos: 20,
        proteinas: 2,
        receta:
          '<div>Ingredientes: 1 manzana, 5 nueces. Preparación: lavar y cortar la manzana, servir con nueces.</div>',
      },
      {
        urlImage: '',
        nombre: 'Pollo con arroz integral',
        descripcion:
          'Pechuga de pollo a la plancha con arroz integral y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 450,
        grasa: 12,
        carbohidratos: 40,
        proteinas: 35,
        receta:
          '<div>Ingredientes: pollo, arroz, verduras. Preparación: cocinar arroz, dorar el pollo, servir con ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Yogur natural con granola',
        descripcion: 'Yogur bajo en grasa con granola casera',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 180,
        grasa: 6,
        carbohidratos: 20,
        proteinas: 10,
        receta:
          '<div>Ingredientes: yogur, granola. Preparación: servir yogur con granola por encima.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de verduras y pan integral',
        descripcion: 'Sopa ligera con pan integral tostado',
        tipo: TipoAlimento.CENA,
        calorias: 300,
        grasa: 5,
        carbohidratos: 30,
        proteinas: 15,
        receta:
          '<div>Ingredientes: verduras, pan integral. Preparación: hervir verduras, servir con pan.</div>',
      },
      {
        urlImage: '',
        nombre: 'Tostadas con palta y huevo',
        descripcion: 'Pan integral con palta y huevo duro',
        tipo: TipoAlimento.DESAYUNO,
        calorias: 300,
        grasa: 15,
        carbohidratos: 25,
        proteinas: 12,
        receta:
          '<div>Ingredientes: pan integral, palta, huevo. Preparación: tostar pan, agregar palta y huevo cocido en rodajas.</div>',
      },
      {
        urlImage: '',
        nombre: 'Banana y almendras',
        descripcion: 'Banana madura con 10 almendras',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 180,
        grasa: 8,
        carbohidratos: 20,
        proteinas: 4,
        receta:
          '<div>Ingredientes: banana, almendras. Preparación: pelar banana y servir con almendras.</div>',
      },
      {
        urlImage: '',
        nombre: 'Carne magra con puré y ensalada',
        descripcion: 'Bistec con puré de papa y ensalada de tomate',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 480,
        grasa: 18,
        carbohidratos: 35,
        proteinas: 35,
        receta:
          '<div>Ingredientes: carne, papa, tomate. Preparación: cocer papa, asar carne, preparar ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Galletas integrales y leche',
        descripcion: 'Galletas de avena con leche descremada',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 200,
        grasa: 7,
        carbohidratos: 30,
        proteinas: 8,
        receta:
          '<div>Ingredientes: galletas, leche. Preparación: servir juntos.</div>',
      },
      {
        urlImage: '',
        nombre: 'Ensalada de atún con galletas saladas',
        descripcion: 'Atún en agua con verduras frescas',
        tipo: TipoAlimento.CENA,
        calorias: 320,
        grasa: 10,
        carbohidratos: 25,
        proteinas: 25,
        receta:
          '<div>Ingredientes: atún, lechuga, tomate, galletas. Preparación: mezclar ingredientes y servir con galletas.</div>',
      },
      {
        urlImage: '',
        nombre: 'Api con buñuelos',
        descripcion: 'Bebida caliente de maíz morado con buñuelos fritos',
        tipo: TipoAlimento.DESAYUNO,
        calorias: 380,
        grasa: 10,
        carbohidratos: 65,
        proteinas: 5,
        receta:
          '<div>Ingredientes: maíz morado, canela, clavo de olor, azúcar, harina, huevo. Preparación: hervir maíz con especias, licuar y colar; freír buñuelos con masa batida.</div>',
      },
      {
        urlImage: '',
        nombre: 'Tucumana de pollo',
        descripcion: 'Empanada frita rellena de pollo y vegetales',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 320,
        grasa: 15,
        carbohidratos: 35,
        proteinas: 10,
        receta:
          '<div>Ingredientes: pollo cocido, papa, cebolla, ají colorado, masa. Preparación: rellenar masa con el preparado y freír.</div>',
      },
      {
        urlImage: '',
        nombre: 'Majadito de charque',
        descripcion: 'Arroz oriental con charque desmenuzado y plátano frito',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 520,
        grasa: 18,
        carbohidratos: 55,
        proteinas: 30,
        receta:
          '<div>Ingredientes: charque, arroz, cebolla, plátano. Preparación: cocinar arroz con charque desmenuzado, freír plátano aparte.</div>',
      },
      {
        urlImage: '',
        nombre: 'Batido de papaya y linaza',
        descripcion: 'Bebida nutritiva con papaya y semillas de linaza',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 190,
        grasa: 5,
        carbohidratos: 30,
        proteinas: 4,
        receta:
          '<div>Ingredientes: papaya, agua, linaza. Preparación: licuar papaya con agua y linaza remojada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de quinua con verduras',
        descripcion: 'Sopa andina con quinua y vegetales',
        tipo: TipoAlimento.CENA,
        calorias: 280,
        grasa: 6,
        carbohidratos: 35,
        proteinas: 10,
        receta:
          '<div>Ingredientes: quinua, zanahoria, arveja, cebolla. Preparación: hervir quinua y verduras en caldo.</div>',
      },
      {
        urlImage: '',
        nombre: 'Pan con queso y mate de coca',
        descripcion: 'Pan con queso fresco y mate de coca',
        tipo: TipoAlimento.DESAYUNO,
        calorias: 260,
        grasa: 10,
        carbohidratos: 30,
        proteinas: 8,
        receta:
          '<div>Ingredientes: pan, queso fresco, hojas de coca. Preparación: servir pan con queso; preparar infusión con coca.</div>',
      },
      {
        urlImage: '',
        nombre: 'Duraznos deshidratados y pasankalla',
        descripcion: 'Frutas secas y maíz reventado',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 170,
        grasa: 3,
        carbohidratos: 35,
        proteinas: 2,
        receta:
          '<div>Ingredientes: durazno deshidratado, pasankalla. Preparación: servir como mezcla seca.</div>',
      },
      {
        urlImage: '',
        nombre: 'Pique macho vegetariano',
        descripcion: 'Versión sin carne del tradicional pique macho',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 460,
        grasa: 14,
        carbohidratos: 50,
        proteinas: 20,
        receta:
          '<div>Ingredientes: salchicha vegetal, papa, locoto, cebolla. Preparación: freír papa, saltear salchicha vegetal con verduras.</div>',
      },
      {
        urlImage: '',
        nombre: 'Gelatina de mocochinchi',
        descripcion: 'Postre con infusión de durazno seco',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 140,
        grasa: 0,
        carbohidratos: 30,
        proteinas: 1,
        receta:
          '<div>Ingredientes: durazno seco (mocochinchi), azúcar, gelatina. Preparación: hervir mocochinchi, colar y mezclar con gelatina.</div>',
      },
      {
        urlImage: '',
        nombre: 'Caldito de cordero con chuño',
        descripcion: 'Caldo con carne de cordero y chuño',
        tipo: TipoAlimento.CENA,
        calorias: 350,
        grasa: 12,
        carbohidratos: 25,
        proteinas: 25,
        receta:
          '<div>Ingredientes: carne de cordero, chuño, cebolla, hierbas. Preparación: hervir carne con chuño y condimentos.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sándwich de chola',
        descripcion: 'Pan con cerdo cocido, escabeche y llajwa',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 360,
        grasa: 14,
        carbohidratos: 35,
        proteinas: 18,
        receta:
          '<div>Ingredientes: pan, carne de cerdo, cebolla, zanahoria. Preparación: cocinar carne, preparar escabeche y armar el sándwich.</div>',
      },
      {
        urlImage: '',
        nombre: 'Empanada salteña',
        descripcion: 'Empanada horneada con carne, papa, huevo y especias',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 320,
        grasa: 12,
        carbohidratos: 30,
        proteinas: 12,
        receta:
          '<div>Ingredientes: masa, carne, papa, huevo, ají. Preparación: preparar relleno jugoso, armar empanadas y hornear.</div>',
      },
      {
        urlImage: '',
        nombre: 'Trucha a la plancha',
        descripcion: 'Trucha fresca con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 400,
        grasa: 15,
        carbohidratos: 25,
        proteinas: 35,
        receta:
          '<div>Ingredientes: trucha, arroz, verduras. Preparación: dorar trucha, servir con arroz y ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Locro de zapallo',
        descripcion: 'Sopa espesa de zapallo, arroz y queso',
        tipo: TipoAlimento.CENA,
        calorias: 300,
        grasa: 10,
        carbohidratos: 40,
        proteinas: 12,
        receta:
          '<div>Ingredientes: zapallo, arroz, queso. Preparación: cocer zapallo con arroz, agregar queso.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de maní',
        descripcion: 'Sopa cremosa con carne, maní y verduras',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 500,
        grasa: 20,
        carbohidratos: 35,
        proteinas: 25,
        receta:
          '<div>Ingredientes: maní, carne, papa, zanahoria. Preparación: licuar maní, hervir con carne y verduras.</div>',
      },
      {
        urlImage: '',
        nombre: "K'allu de tomate y queso",
        descripcion: 'Ensalada simple con tomate, queso y cebolla',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 160,
        grasa: 6,
        carbohidratos: 10,
        proteinas: 8,
        receta:
          '<div>Ingredientes: tomate, queso fresco, cebolla. Preparación: cortar en rodajas y servir con sal.</div>',
      },
      {
        urlImage: '',
        nombre: 'Mocochinchi',
        descripcion: 'Bebida refrescante de durazno seco',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 120,
        grasa: 0,
        carbohidratos: 30,
        proteinas: 1,
        receta:
          '<div>Ingredientes: durazno seco, canela, azúcar. Preparación: hervir durazno con canela, enfriar.</div>',
      },
      {
        urlImage: '',
        nombre: 'Falso conejo',
        descripcion: 'Filete apanado con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 460,
        grasa: 18,
        carbohidratos: 40,
        proteinas: 25,
        receta:
          '<div>Ingredientes: carne, pan molido, arroz, lechuga. Preparación: empanar y freír carne, servir con guarnición.</div>',
      },
      {
        urlImage: '',
        nombre: 'Papas a la huancaína boliviana',
        descripcion: 'Papas cocidas con salsa de maní o queso',
        tipo: TipoAlimento.CENA,
        calorias: 280,
        grasa: 10,
        carbohidratos: 30,
        proteinas: 10,
        receta:
          '<div>Ingredientes: papa, queso, maní, leche. Preparación: cocer papa y cubrir con salsa.</div>',
      },
      {
        urlImage: '',
        nombre: 'Ají de lentejas',
        descripcion: 'Estofado de lentejas con arroz y huevo',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 390,
        grasa: 12,
        carbohidratos: 40,
        proteinas: 20,
        receta:
          '<div>Ingredientes: lentejas, arroz, huevo. Preparación: cocer lentejas y arroz, servir con huevo duro.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sándwich de chola #2',
        descripcion: 'Pan con cerdo cocido, escabeche y llajwa',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 360,
        grasa: 14,
        carbohidratos: 35,
        proteinas: 18,
        receta:
          '<div>Ingredientes: pan, carne de cerdo, cebolla, zanahoria. Preparación: cocinar carne, preparar escabeche y armar el sándwich.</div>',
      },
      {
        urlImage: '',
        nombre: 'Empanada salteña #2',
        descripcion: 'Empanada horneada con carne, papa, huevo y especias',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 320,
        grasa: 12,
        carbohidratos: 30,
        proteinas: 12,
        receta:
          '<div>Ingredientes: masa, carne, papa, huevo, ají. Preparación: preparar relleno jugoso, armar empanadas y hornear.</div>',
      },
      {
        urlImage: '',
        nombre: 'Trucha a la plancha #2',
        descripcion: 'Trucha fresca con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 400,
        grasa: 15,
        carbohidratos: 25,
        proteinas: 35,
        receta:
          '<div>Ingredientes: trucha, arroz, verduras. Preparación: dorar trucha, servir con arroz y ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Locro de zapallo #2',
        descripcion: 'Sopa espesa de zapallo, arroz y queso',
        tipo: TipoAlimento.CENA,
        calorias: 300,
        grasa: 10,
        carbohidratos: 40,
        proteinas: 12,
        receta:
          '<div>Ingredientes: zapallo, arroz, queso. Preparación: cocer zapallo con arroz, agregar queso.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de maní #2',
        descripcion: 'Sopa cremosa con carne, maní y verduras',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 500,
        grasa: 20,
        carbohidratos: 35,
        proteinas: 25,
        receta:
          '<div>Ingredientes: maní, carne, papa, zanahoria. Preparación: licuar maní, hervir con carne y verduras.</div>',
      },
      {
        urlImage: '',
        nombre: "K'allu de tomate y queso #2",
        descripcion: 'Ensalada simple con tomate, queso y cebolla',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 160,
        grasa: 6,
        carbohidratos: 10,
        proteinas: 8,
        receta:
          '<div>Ingredientes: tomate, queso fresco, cebolla. Preparación: cortar en rodajas y servir con sal.</div>',
      },
      {
        urlImage: '',
        nombre: 'Mocochinchi #2',
        descripcion: 'Bebida refrescante de durazno seco',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 120,
        grasa: 0,
        carbohidratos: 30,
        proteinas: 1,
        receta:
          '<div>Ingredientes: durazno seco, canela, azúcar. Preparación: hervir durazno con canela, enfriar.</div>',
      },
      {
        urlImage: '',
        nombre: 'Falso conejo #2',
        descripcion: 'Filete apanado con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 460,
        grasa: 18,
        carbohidratos: 40,
        proteinas: 25,
        receta:
          '<div>Ingredientes: carne, pan molido, arroz, lechuga. Preparación: empanar y freír carne, servir con guarnición.</div>',
      },
      {
        urlImage: '',
        nombre: 'Papas a la huancaína boliviana #2',
        descripcion: 'Papas cocidas con salsa de maní o queso',
        tipo: TipoAlimento.CENA,
        calorias: 280,
        grasa: 10,
        carbohidratos: 30,
        proteinas: 10,
        receta:
          '<div>Ingredientes: papa, queso, maní, leche. Preparación: cocer papa y cubrir con salsa.</div>',
      },
      {
        urlImage: '',
        nombre: 'Ají de lentejas #2',
        descripcion: 'Estofado de lentejas con arroz y huevo',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 390,
        grasa: 12,
        carbohidratos: 40,
        proteinas: 20,
        receta:
          '<div>Ingredientes: lentejas, arroz, huevo. Preparación: cocer lentejas y arroz, servir con huevo duro.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sándwich de chola #3',
        descripcion: 'Pan con cerdo cocido, escabeche y llajwa',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 360,
        grasa: 14,
        carbohidratos: 35,
        proteinas: 18,
        receta:
          '<div>Ingredientes: pan, carne de cerdo, cebolla, zanahoria. Preparación: cocinar carne, preparar escabeche y armar el sándwich.</div>',
      },
      {
        urlImage: '',
        nombre: 'Empanada salteña #3',
        descripcion: 'Empanada horneada con carne, papa, huevo y especias',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 320,
        grasa: 12,
        carbohidratos: 30,
        proteinas: 12,
        receta:
          '<div>Ingredientes: masa, carne, papa, huevo, ají. Preparación: preparar relleno jugoso, armar empanadas y hornear.</div>',
      },
      {
        urlImage: '',
        nombre: 'Trucha a la plancha #3',
        descripcion: 'Trucha fresca con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 400,
        grasa: 15,
        carbohidratos: 25,
        proteinas: 35,
        receta:
          '<div>Ingredientes: trucha, arroz, verduras. Preparación: dorar trucha, servir con arroz y ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Locro de zapallo #3',
        descripcion: 'Sopa espesa de zapallo, arroz y queso',
        tipo: TipoAlimento.CENA,
        calorias: 300,
        grasa: 10,
        carbohidratos: 40,
        proteinas: 12,
        receta:
          '<div>Ingredientes: zapallo, arroz, queso. Preparación: cocer zapallo con arroz, agregar queso.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de maní #3',
        descripcion: 'Sopa cremosa con carne, maní y verduras',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 500,
        grasa: 20,
        carbohidratos: 35,
        proteinas: 25,
        receta:
          '<div>Ingredientes: maní, carne, papa, zanahoria. Preparación: licuar maní, hervir con carne y verduras.</div>',
      },
      {
        urlImage: '',
        nombre: "K'allu de tomate y queso #3",
        descripcion: 'Ensalada simple con tomate, queso y cebolla',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 160,
        grasa: 6,
        carbohidratos: 10,
        proteinas: 8,
        receta:
          '<div>Ingredientes: tomate, queso fresco, cebolla. Preparación: cortar en rodajas y servir con sal.</div>',
      },
      {
        urlImage: '',
        nombre: 'Mocochinchi #3',
        descripcion: 'Bebida refrescante de durazno seco',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 120,
        grasa: 0,
        carbohidratos: 30,
        proteinas: 1,
        receta:
          '<div>Ingredientes: durazno seco, canela, azúcar. Preparación: hervir durazno con canela, enfriar.</div>',
      },
      {
        urlImage: '',
        nombre: 'Falso conejo #3',
        descripcion: 'Filete apanado con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 460,
        grasa: 18,
        carbohidratos: 40,
        proteinas: 25,
        receta:
          '<div>Ingredientes: carne, pan molido, arroz, lechuga. Preparación: empanar y freír carne, servir con guarnición.</div>',
      },
      {
        urlImage: '',
        nombre: 'Papas a la huancaína boliviana #3',
        descripcion: 'Papas cocidas con salsa de maní o queso',
        tipo: TipoAlimento.CENA,
        calorias: 280,
        grasa: 10,
        carbohidratos: 30,
        proteinas: 10,
        receta:
          '<div>Ingredientes: papa, queso, maní, leche. Preparación: cocer papa y cubrir con salsa.</div>',
      },
      {
        urlImage: '',
        nombre: 'Ají de lentejas #3',
        descripcion: 'Estofado de lentejas con arroz y huevo',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 390,
        grasa: 12,
        carbohidratos: 40,
        proteinas: 20,
        receta:
          '<div>Ingredientes: lentejas, arroz, huevo. Preparación: cocer lentejas y arroz, servir con huevo duro.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sándwich de chola #4',
        descripcion: 'Pan con cerdo cocido, escabeche y llajwa',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 360,
        grasa: 14,
        carbohidratos: 35,
        proteinas: 18,
        receta:
          '<div>Ingredientes: pan, carne de cerdo, cebolla, zanahoria. Preparación: cocinar carne, preparar escabeche y armar el sándwich.</div>',
      },
      {
        urlImage: '',
        nombre: 'Empanada salteña #4',
        descripcion: 'Empanada horneada con carne, papa, huevo y especias',
        tipo: TipoAlimento.MEDIA_MANIANA,
        calorias: 320,
        grasa: 12,
        carbohidratos: 30,
        proteinas: 12,
        receta:
          '<div>Ingredientes: masa, carne, papa, huevo, ají. Preparación: preparar relleno jugoso, armar empanadas y hornear.</div>',
      },
      {
        urlImage: '',
        nombre: 'Trucha a la plancha #4',
        descripcion: 'Trucha fresca con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 400,
        grasa: 15,
        carbohidratos: 25,
        proteinas: 35,
        receta:
          '<div>Ingredientes: trucha, arroz, verduras. Preparación: dorar trucha, servir con arroz y ensalada.</div>',
      },
      {
        urlImage: '',
        nombre: 'Locro de zapallo #4',
        descripcion: 'Sopa espesa de zapallo, arroz y queso',
        tipo: TipoAlimento.CENA,
        calorias: 300,
        grasa: 10,
        carbohidratos: 40,
        proteinas: 12,
        receta:
          '<div>Ingredientes: zapallo, arroz, queso. Preparación: cocer zapallo con arroz, agregar queso.</div>',
      },
      {
        urlImage: '',
        nombre: 'Sopa de maní #4',
        descripcion: 'Sopa cremosa con carne, maní y verduras',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 500,
        grasa: 20,
        carbohidratos: 35,
        proteinas: 25,
        receta:
          '<div>Ingredientes: maní, carne, papa, zanahoria. Preparación: licuar maní, hervir con carne y verduras.</div>',
      },
      {
        urlImage: '',
        nombre: "K'allu de tomate y queso #4",
        descripcion: 'Ensalada simple con tomate, queso y cebolla',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 160,
        grasa: 6,
        carbohidratos: 10,
        proteinas: 8,
        receta:
          '<div>Ingredientes: tomate, queso fresco, cebolla. Preparación: cortar en rodajas y servir con sal.</div>',
      },
      {
        urlImage: '',
        nombre: 'Mocochinchi #4',
        descripcion: 'Bebida refrescante de durazno seco',
        tipo: TipoAlimento.MEDIA_TARDE,
        calorias: 120,
        grasa: 0,
        carbohidratos: 30,
        proteinas: 1,
        receta:
          '<div>Ingredientes: durazno seco, canela, azúcar. Preparación: hervir durazno con canela, enfriar.</div>',
      },
      {
        urlImage: '',
        nombre: 'Falso conejo #4',
        descripcion: 'Filete apanado con arroz y ensalada',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 460,
        grasa: 18,
        carbohidratos: 40,
        proteinas: 25,
        receta:
          '<div>Ingredientes: carne, pan molido, arroz, lechuga. Preparación: empanar y freír carne, servir con guarnición.</div>',
      },
      {
        urlImage: '',
        nombre: 'Papas a la huancaína boliviana #4',
        descripcion: 'Papas cocidas con salsa de maní o queso',
        tipo: TipoAlimento.CENA,
        calorias: 280,
        grasa: 10,
        carbohidratos: 30,
        proteinas: 10,
        receta:
          '<div>Ingredientes: papa, queso, maní, leche. Preparación: cocer papa y cubrir con salsa.</div>',
      },
      {
        urlImage: '',
        nombre: 'Ají de lentejas #4',
        descripcion: 'Estofado de lentejas con arroz y huevo',
        tipo: TipoAlimento.ALMUERZO,
        calorias: 390,
        grasa: 12,
        carbohidratos: 40,
        proteinas: 20,
        receta:
          '<div>Ingredientes: lentejas, arroz, huevo. Preparación: cocer lentejas y arroz, servir con huevo duro.</div>',
      },
    ]
    const alimentos = items.map((item) => {
      return new Alimento({
        ...item,
        estado: AlimentoEstado.ACTIVO,
        transaccion: 'SEEDS',
        usuarioCreacion: USUARIO_SISTEMA,
      })
    })
    await queryRunner.manager.save(alimentos)
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  public async down(queryRunner: QueryRunner): Promise<void> {}
}
