include:
  - /.gitlab/k8s-testing.yml

stages:
  - prebuild
  - build
  - test
  - sast
  - release
  - deploy
  - dast
  - setup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CI_PROJECT_NAME: $PROJECT_NAME

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull
