FROM hub.agcs.agetic.gob.bo/dockerhub-proxy/library/node:20-alpine AS base
WORKDIR /home/node/app

RUN mkdir -p node_modules && \
    chown -R node:node /home/node

COPY --chown=node:node --link package*.json ./

USER node

RUN npm set registry https://registry.agcs.agetic.gob.bo/ && \
    npm set strict-ssl false
    
RUN npm ci --prefer-offline --progress=false --no-audit 

USER root
RUN npm install -g turbo

FROM base AS merge
COPY --chown=node:node --link . .
ARG TURBO_API
ARG TURBO_TEAM
ARG TURBO_TOKEN
ENV TURBO_TELEMETRY_DISABLED=${TURBO_TELEMETRY_DISABLED}
ENV DO_NOT_TRACK=${DO_NOT_TRACK}
ENV TURBO_API=${TURBO_API}
ENV TURBO_TEAM=${TURBO_TEAM}
ENV TURBO_TOKEN=${TURBO_TOKEN}
RUN npm run format-check
RUN turbo build-docker
