export enum RolEnum {
  PACIENTE = 'PACIENTE',
  NUTRICIONISTA = 'NUTRICIONISTA',
  ADMINISTRADOR = 'ADMINISTRADOR',
  TODOS = '*',
}

export enum RolEnumId {
  ADMINISTRADOR = '1',
  NUTRICIONISTA = '2',
  PACIENTE = '3',
}
