export enum RolEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  SUPERVISOR = 'SUPERVISOR',
  PERSONAL_MEDICO = 'PERSONAL_MEDICO',
  PACIENTE = 'PACIENTE',
  TODOS = '*',
}

export enum RolEnumId {
  ADMINISTRADOR = '1',
  SUPERVISOR = '2',
  PERSONAL_MEDICO = '3',
  PACIENTE = '4',
}
