export enum RolEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  JEFE = 'JEFE',
  COORDINADOR = 'COORDINADOR',
  PERSONAL = 'PERSONAL',
  PROFESIONAL_INVITADO = 'PROFESIONAL_INVITADO',
  TODOS = '*',
}

export enum RolEnumId {
  ADMINISTRADOR = '1',
  JEFE = '2',
  COORDINADOR = '3',
  PERSONAL = '4',
  PROFESIONAL_INVITADO = '5',
}
